/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "nova.api.": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        },
        {
            "name": "relatedResource",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "vapor-ui": [
        {
            "name": "view",
            "required": false
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "nova.pages.login": [],
    "nova.login": [],
    "nova.logout": [],
    "nova.pages.password.email": [],
    "nova.password.email": [],
    "nova.pages.password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "nova.password.reset": [],
    "nova.pages.403": [],
    "nova.pages.404": [],
    "nova.pages.home": [],
    "nova.pages.dashboard": [],
    "nova.pages.dashboard.custom": [
        {
            "name": "name",
            "required": true
        }
    ],
    "nova.pages.index": [
        {
            "name": "resource",
            "required": true
        }
    ],
    "nova.pages.create": [
        {
            "name": "resource",
            "required": true
        }
    ],
    "nova.pages.detail": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        }
    ],
    "nova.pages.edit": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        }
    ],
    "nova.pages.replicate": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        }
    ],
    "nova.pages.lens": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "lens",
            "required": true
        }
    ],
    "nova.pages.attach": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        },
        {
            "name": "relatedResource",
            "required": true
        }
    ],
    "nova.pages.edit-attached": [
        {
            "name": "resource",
            "required": true
        },
        {
            "name": "resourceId",
            "required": true
        },
        {
            "name": "relatedResource",
            "required": true
        },
        {
            "name": "relatedResourceId",
            "required": true
        }
    ],
    "api.games.info": [
        {
            "name": "game",
            "required": true,
            "binding": "uuid"
        }
    ],
    "api.game.stats": [
        {
            "name": "game",
            "required": true,
            "binding": "uuid"
        }
    ],
    "api.game.create": [],
    "api.user.info": [
        {
            "name": "user",
            "required": true,
            "binding": "username"
        }
    ],
    "home": [],
    "game.create": [],
    "game.play": [
        {
            "name": "game",
            "required": true,
            "binding": "uuid"
        }
    ],
    "game.solve": [
        {
            "name": "game",
            "required": true,
            "binding": "uuid"
        }
    ],
    "register": [],
    "login": [],
    "verify-login": [
        {
            "name": "token",
            "required": true
        }
    ],
    "logout": []
}
}
export {};
